# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SongodaCore

on:
  push:
    branches: [ master, development ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout project files
      - uses: actions/checkout@v2

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: maven

      # Build Spigot 1.18.2 (remapped)
      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19
          remapped: true

      # Build project
      - name: Build with Maven
        run: 'mvn clean package'

      # Upload build artifacts
      - name: 'Upload Build Artifact: SongodaCore-*.jar'
        uses: actions/upload-artifact@v2
        with:
          name: SongodaCore-artifacts
          path: ./Core/target/SongodaCore-*.jar